on:
  schedule:
    - cron: 0 0 1 * * # midnight on 1st of month
  workflow_dispatch: 
    inputs:
      release:
        description: "Make a new GitHub/Zenodo release with this run?"
        required: true
        type: boolean

name: run_workflow.yml

jobs:
  states:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        state: ["DE", "RI"]
        # state: ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::purrr
            any::nanoparquet
            any::fs
            github::Evans-Ecology-Lab/forestTIME-builder
      
      - name: Generate state parquet
        run: Rscript state-parquet.R
        env:
          STATE: ${{ matrix.state }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.state }}
          path: fia/parquet/*

  release:
  # only happens if schedule or workflow_dispatch with release=TRUE
    if: ${{ (inputs.release && github.event_name == 'workflow_dispatch') || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    needs: states
    permissions:
      contents: write #allow writing commits
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: fia/parquet
          merge-multiple: true

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::cffr
            any::lubridate

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # - name: 'Get previous release tag'
      #   run: |
      #     echo "PREV_RELEASE=$(gh release list --json tagName,isLatest --jq '.[] | select(.isLatest)|.tagName')" >> $GITHUB_ENV
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update metadata
        run: |
          Rscript update_metadata.R
          echo ${{ env.RELEASE }}
        # env:
        #   PREV_RELEASE: ${{ env.PREV_RELEASE }}

      # commit changes to metadata
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update dataset version and release date
        
      - name: Create Tag
        run: |
          git tag -a "$RELEASE" -m "Automatic release $RELEASE"
          git push origin $RELEASE
        env:
          RELEASE: ${{ env.RELEASE }}

      # Create a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE }}
          name: "Automatic Release ${{ env.RELEASE }}" #TODO different title if workflow_dispatch
          body: "Monthly release of annualized FIADB tables" #TODO different message if workflow_dispatch
          artifacts: fia/parquet/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}