on:
  schedule:
    - cron: 0 0 1 * * # midnight on 1st of month
  workflow_dispatch: 
    inputs:
      release:
        description: "Make a new GitHub/Zenodo release with this run?"
        required: true
        type: boolean

name: run_workflow.yml

jobs:
  states:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        state: ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::dplyr
            any::purrr
            any::nanoparquet
            any::fs
            any::cli
            github::Evans-Ecology-Lab/forestTIME-builder
      
      - name: Generate state parquet
        run: Rscript state-parquet.R
        env:
          STATE: ${{ matrix.state }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.state }}
          path: fia/parquet/*

    # release:
    #   # only happens if schedule or workflow_dispatch with release=TRUE
    #   runs-on: ubuntu-latest
    #   needs: states
    #   steps:
    #     - name: Update metadata
    #     # Update zenodo.json and/or CITATION.cff
    #     - name: Create release
    #     # Increment version, add artifacts to release, possibly as a single zip file
    #     # Make release with timestamp as version