on:
  schedule:
    - cron: 0 0 1 * * # midnight on 1st of month
  workflow_dispatch:

name: run_workflow.yml

jobs:
  states:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        state: ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::dplyr
            any::purrr
            any::nanoparquet
            any::fs
            any::cli
            github::Evans-Ecology-Lab/forestTIME-builder
      
      - name: Generate state parquet
        run: Rscript state-parquet.R
        env:
          STATE: ${{ matrix.state }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.state }}
          path: fia/parquet/*
  #TODO update zenodo.json and/or CITATION.cff
  combine:
    runs-on: ubuntu-latest
    needs: states
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: fia/parquet
          merge-multiple: true
      - name: Create zip file
        run: zip -r all_states.zip fia/parquet
        #TODO: add artifact to GitHub release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: all_states.zip
          path: all_states.zip
        #TODO: make github release with timestamp