on:
  schedule:
    - cron: 0 0 1 * * # midnight on 1st of month
  workflow_dispatch: 
    inputs:
      release:
        description: "Make a new GitHub/Zenodo release with this run?"
        required: true
        type: boolean

name: run_workflow.yml

jobs:
 states:
    timeout-minutes: 2160
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        state: ["WI", "TX"]
        year_var: ["INVYR", "MEASYEAR"]
        #state: ["AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
    container:
      image: ghcr.io/devinbayly/foresttime-hpc@sha256:57038b4708f1ef1e5628c6211141cee6810d1d210efb823c6cd290b961e93170
    steps:
      - uses: actions/checkout@v4
      - name: check directory contents
        run: ls -rtlha
      - name: install forestTIME
        run: R -e "pak::pak('Evans-Ecology-Lab/forestTIME#232')"
      - name: Generate state parquet
        run: Rscript state-parquet-v2.R
        env:
          STATE: ${{ matrix.state }}
          YEAR_VAR: ${{ matrix.year_var }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.state }}_${{ matrix.year_var }}
          path: fia/parquet/${{ matrix.state }}  
          
 release:
    needs: states
  # only happens if schedule or workflow_dispatch with release=TRUE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: "fia/parquet"
          github-token: ${{ secrets.GH_TOKEN }}
          merge-multiple: true

      - name: Total release size
        run: ls fia/parquet -rtlh
      - name: upload with python zenodo
        run: python3 zenodo-api.py
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
  
